# Local testing
# $> docker run --name travis-debug -dit travisci/ci-garnet:packer-1512502276-986baf0 /sbin/init
# $> docker exec -it travis-debug bash -l
# $> su - travis
# $> git clone --depth=50 --branch=master https://github.com/aarongustafson/aarongustafson.github.io.git
# Manually run the commands to build this project
language: ruby
rvm:
  - 2.4
cache: bundler

addons:
  ssh_known_hosts:
  - 45.55.195.184

before_install: 
  - chmod +x .travis/*.sh
  - openssl aes-256-cbc -K $encrypted_bb5b178a0863_key -iv $encrypted_bb5b178a0863_iv -in .travis/id_rsa_travis.enc -out .travis/id_rsa -d
install: .travis/install.sh
script: .travis/build.sh

# branch whitelist
branches:
  only:
  - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
