language: ruby
rvm:
- 2.3

before_install: .travis/before-install.sh
install: .travis/install.sh
script: .travis/build.sh

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: gh-pages