language: ruby
rvm:
- 2.3

before_install: 
  - chmod +x .travis/*.sh
  - openssl aes-256-cbc -K $encrypted_bb5b178a0863_key -iv $encrypted_bb5b178a0863_iv -in .travis/id_rsa_travis.enc -out .travis/id_rsa -d
install: .travis/install.sh
script: .travis/build.sh

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master