# To launch: docker-compose run jekyll bash
jekyll:
    image: jekyll/jekyll
    command: bash -c "apk --update add alpine-sdk ruby-dev lapack@communityEdge lapack-dev@communityEdge imagemagick-dev && bundle install && bundle exec jekyll serve --watch --incremental"
    #command: bash -c "apk --update add alpine-sdk ruby-dev lapack@communityEdge imagemagick-dev && bundle install"
    environment:
        - BUFFER_CLIENT_ID
        - BUFFER_CLIENT_SECRET
        - BUFFER_ACCESS_TOKEN
        - BUFFER_FACEBOOK_PROFILE
        - BUFFER_LINKEDIN_PROFILE
        - BUFFER_TWITTER_PROFILE
        - TWITTER_CONSUMER_SECRET
        - TWITTER_ACCESS_TOKEN
        - TWITTER_CONSUMER_KEY
        - MEDIUM_USER_ID
        - MEDIUM_INTEGRATION_TOKEN
        - GOOGLE_API_KEY
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll